[package]
name = "stardust-xr-atmosphere"
version = "0.4.0"
edition = "2021"
description = "Stardust XR's reference environment/homespace client"
authors = ["Nova King <technobaboo@proton.me>"]
license = "MIT"
repository = "https://github.com/StardustXR/atmosphere"

[[bin]]
name = "atmosphere"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.24.2", features = ["full"] }
glam = { version = "0.22.0", features = ["mint"] }
mint = { version = "0.5.9", features = ["serde"] }
stardust-xr-fusion = "0.34.0"
confy = "0.5.1"
serde = { version = "1.0.152", features = ["derive"] }
toml = { version = "0.6.0", features = ["preserve_order"] }
rustc-hash = "1.1.0"
dirs = "4.0.0"
color-eyre = "0.6.2"
