[package]
name = "stardust-xr-atmosphere"
version = "0.3.0"
edition = "2021"
description = "Stardust XR's reference environment/homespace client"
authors = ["Nova King <technobaboo@proton.me>"]
license = "MIT"
repository = "https://github.com/StardustXR/atmosphere"

[[bin]]
name = "atmosphere"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
glam = { version = "0.22.0", features = ["mint"] }
mint = { version = "0.5.9", features = ["serde"] }
stardust-xr-fusion = "0.25.5"
confy = "0.5.0"
serde = { version = "1.0.145", features = ["derive"] }
toml = { version = "0.5.9", features = ["preserve_order"] }
anyhow = "1.0.65"
rustc-hash = "1.1.0"
dirs = "4.0.0"
