[package]
name = "stardust-xr-atmosphere"
version = "0.4.0"
edition = "2021"
description = "Stardust XR's reference environment/homespace client"
authors = ["Nova King <technobaboo@proton.me>"]
license = "MIT"
repository = "https://github.com/StardustXR/atmosphere"

[[bin]]
name = "atmosphere"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
glam = { version = "0.24.2", features = ["mint"] }
mint = { version = "0.5.9", features = ["serde"] }
stardust-xr-fusion = "0.43.2"
confy = "0.5.1"
serde = { version = "1.0.188", features = ["derive"] }
toml = { version = "0.8.0", features = ["preserve_order"] }
rustc-hash = "1.1.0"
dirs = "5.0.1"
color-eyre = "0.6.2"
clap = { version = "4.4.4", features = ["derive"] }
copy_dir = "0.1.3"
stardust-xr-molecules = "0.29.0"
